### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by zcdliuwei** [jo-lang/traversing_designspaces#2]
Hello, what an interesting display!
And I want to know, where is the listfontvariables function, I'm sorry I didn't find it.
Looking forward to your reply, thank you

**Comment by jo-lang** [comment]
hi, great if you like it! 
you will need the [drawbot app](https://github.com/typemytype/drawbot/) for these scripts. 
If you are looking for the ```listFontVariations``` they are built into [drawbot](https://github.com/typemytype/drawbot/blob/a9168ebcfcc0d0f48403e657ecd7191d5113fd62/drawBot/context/baseContext.py#L1612).
 hope that helps?

**Comment by zcdliuwei** [comment]
> hi, great if you like it!
> you will need the [drawbot app](https://github.com/typemytype/drawbot/) for these scripts.
> If you are looking for the `listFontVariations` they are built into [drawbot](https://github.com/typemytype/drawbot/blob/a9168ebcfcc0d0f48403e657ecd7191d5113fd62/drawBot/context/baseContext.py#L1612).
> hope that helps?
Hello, I'm so excited to see your timely and useful reply.
In addition, there are many functions that can't be found, such as fill(), strokewidth(), font(), stroke(), etc
I really like the font design you showed， I hope we can have more discussions，Thanks again. Have a nice day!

**Comment by jo-lang** [comment]
hi, these scripts are not pure python. as mentioned above you will need the drawbotapp to run them 
all the functions you are missing are built into it.
